### ISSUE TITLE
Code challenge is missing

### ISSUE THREAD

**Issue by orangevinz** [bastiaandewaele/tiktok-oauth2-v1#5]
Following your demo code I have this screen/error saying

> Unable to connect to TikTok. This may be due to specific application settings.
If you're a developer, fix the following and try again:
code_challenge

![image](https://github.com/bastiaandewaele/oauth2-tiktok/assets/1336194/f78f941d-e28d-446a-8005-846fe2d27d96)

```php
#[Route(path: '/', name:'test_auth', host: 'localhost')]
    public function index(): Response
    {
        $provider = new TikTokAuthProvider([
            'clientId' => 'xxxxxx',
            'clientSecret' => 'xxxxxx',
            'redirectUri' => 'https://localhost:22443/public/external-account/connect-check/'
        ]);

        if (!isset($_GET['code'])) {
            // If we don't have an authorization code then get one
            $authUrl = $provider->getAuthorizationUrl();
            $_SESSION['oauth2state'] = $provider->getState();

            header('Location: '.$authUrl);
            exit;

        // Check given state against previously stored one to mitigate CSRF attack
        } elseif (empty($_GET['state']) || ($_GET['state'] !== $_SESSION['oauth2state'])) {

            unset($_SESSION['oauth2state']);
            exit('Invalid state');

        } else {
            // Try to get an access token (using the authorization code grant)
            $token = $provider->getAccessToken('authorization_code', [
                'code' => $_GET['code']
            ]);

            // Optional: Now you have a token you can look up a users profile data
            try {

                // We got an access token, let's now get the user's details
                $team = $provider->getResourceOwner($token);

                // Use these details to create a new profile
                printf('Hello %s!', $team->getName());

            } catch (Exception $e) {

                // Failed to get user details
                exit('Oh dear...');
            }

            // Use this to interact with an API on the users behalf
            echo $token->getToken();
        }

        dd('ok');
    }
```

Did I forget somethting ?

**Comment by bastiaandewaele** [comment]
Such errors could only happen when the `clientId` or `redirectUri` are incorrect. Or your application is missing one of these scopes:

- user.info.basic
- video.list
- video.upload
- video.publish

You can limit your scopes by doing this: 

```php
$authUrl = $provider->getAuthorizationUrl(['scope' => ['scope1']]);
```

**Comment by orangevinz** [comment]
Thanks @bastiaandewaele , indeed `localhost:22443` was not registered as a valid redirection in the tiktok dashbard.
Now I set and use a `domain.local` but I'm facing the `redirect_uri`  issue.

I know it's not related to your library but can you tell me if
- you can use a domain.local:4242 with a custom port
- you can work locally with your app in staging mode

It seems tiktok is not very handy to work locally, in dev environment: https://stackoverflow.com/questions/73338099/tiktok-login-kit-web-flow-keep-getting-redirect-uri-error-code-10006

Thanks for your help

**Comment by bastiaandewaele** [comment]
I will take a look at it Tonight or tomorrow.

**Comment by bastiaandewaele** [comment]
I am not sure (asked around), but staging mode should work locally.

But I think the port shouldn't be there.

What happens with the redirect? The port is gone, HTTPS has been added to the URL?

**Comment by orangevinz** [comment]
I confirm that as soon as I switch to **production** mode (after the validaton process), the `redirect_uri` issue disappeared.

And locally I had to remove the port to have an url like this: `https://api.xxx.local/public/external-account/connect-check/`
to make it work
